version: '3'

services:
  server:
    image: ghcr.io/thornjad/karlsfriendshipregain
    restart: unless-stopped
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
